<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Snappy PDF / Image Configuration
    |--------------------------------------------------------------------------
    |
    | This option contains settings for PDF generation.
    |
    | Enabled:
    |
    |    Whether to load PDF / Image generation.
    |
    | Binary:
    |
    |    The file path of the wkhtmltopdf / wkhtmltoimage executable.
    |
    | Timout:
    |
    |    The amount of time to wait (in seconds) before PDF / Image generation is stopped.
    |    Setting this to false disables the timeout (unlimited processing time).
    |
    | Options:
    |
    |    The wkhtmltopdf command options. These are passed directly to wkhtmltopdf.
    |    See https://wkhtmltopdf.org/usage/wkhtmltopdf.txt for all options.
    |
    | Env:
    |
    |    The environment variables to set while running the wkhtmltopdf process.
    |
            'binary'  => env('WKHTML_PDF_BINARY', '/usr/local/bin/wkhtmltopdf'),
            'binary'  => env('WKHTML_IMG_BINARY', '/usr/local/bin/wkhtmltoimage'),

    */


    'pdf' => [
        'enabled' => true,
        'binary'  =>env('WKHTML_PDF_BINARY', '/usr/bin/wkhtmltopdf'),
        'timeout' => false,
        'options' => [
            'enable-local-file-access' => true,
            'orientation'   => 'portrait',
            'encoding'      => 'UTF-8',
            'debug-javascript' => true,
            'enable-javascript' => true,
            'javascript-delay' => 1000,
            'enable-smart-shrinking'=> true,
            'no-stop-slow-scripts' => true,
            'footer-html' => (function () {
                $logoPath = public_path('img/logo-imis.png');
                $imgTag   = file_exists($logoPath)
                    ? '<img src="data:image/png;base64,' . base64_encode(file_get_contents($logoPath)) . '" style="height:26px;vertical-align:middle;margin-left:8px;">'
                    : '';
                $html = '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:4px 10px;font-family:Courier;font-size:10pt;">'
                    . '<table width="100%" cellpadding="0" cellspacing="0"><tr>'
                    // . '<td>System Generated on ' . date('Y-m-d') . '</td>'
                    . '<td align="right" style="white-space:nowrap;">This Report is Generated by ' . $imgTag . '</td>'
                    . '</tr></table></body></html>';
                $tmpFile = sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'pdf_footer_' . md5($html) . '.html';
                file_put_contents($tmpFile, $html);
                return $tmpFile;
            })()
        ],
        'env'     => [],
    ],
    'image' => [
        'enabled' => true,
        'binary' => env('WKHTML_IMG_BINARY', '/usr/bin/wkhtmltoimage'),
        'timeout' => false,
        'options' => [
            'enable-local-file-access' => true,
            'orientation'   => 'portrait',
            'encoding'      => 'UTF-8'
        ],
        'env'     => [],
    ],
];

